"use client";

import { useState, type FormEvent } from "react";
import { ActionButton } from "@/app/components/action-button";
import { createClient } from "@/app/admin/actions";

type Errors = Partial<Record<"clientName" | "email" | "scope", string>>;
export function NewClientForm({ serverError }: { serverError?: string }) {
  const [errors, setErrors] = useState<Errors>({});
  function validate(event: FormEvent<HTMLFormElement>) {
    const data = new FormData(event.currentTarget); const next: Errors = {};
    if (!String(data.get("clientName") ?? "").trim()) next.clientName = "Business/client name is required.";
    if (!String(data.get("email") ?? "").trim()) next.email = "Contact email is required.";
    if (!String(data.get("scope") ?? "").trim()) next.scope = "Service purchased is required.";
    setErrors(next); if (Object.keys(next).length) event.preventDefault();
  }
  return <form action={createClient} onSubmit={validate} noValidate className="mt-8 grid gap-6 lg:grid-cols-[1fr_300px]"><section className="space-y-5 rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="font-semibold">1. Client profile</h2>{serverError && <p role="alert" className="rounded-md border border-amber-900/60 bg-amber-950/30 p-3 text-sm text-amber-100">{serverError}</p>}<p className="text-sm text-zinc-400"><span className="text-amber-200">*</span> Required fields</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Business/client name" name="clientName" required error={errors.clientName} /><Field label="Contact name" name="contactName" /><Field label="Contact email" name="email" type="email" required error={errors.email} /><Field label="Client type" name="clientType" placeholder="e.g. Real estate, E-commerce, Healthcare" /><Field label="Market/country" name="market" placeholder="IN" /><Field label="IANA time zone" name="timezone" placeholder="Asia/Kolkata" /><Field label="Preferred language" name="locale" placeholder="Optional" /><Field label="Sales owner" name="owner" placeholder="Optional" /></div><label className="block text-sm">Internal note<textarea name="note" className="mt-2 min-h-20 w-full rounded-md border border-zinc-700 bg-zinc-900 p-3" /></label><h2 className="pt-3 font-semibold">2. Service purchased</h2><label className="block text-sm">Connection scope <span className="text-amber-200">*</span><select name="scope" defaultValue="whatsapp" aria-invalid={Boolean(errors.scope)} aria-describedby={errors.scope ? "scope-error" : undefined} className="mt-2 w-full rounded-md border border-zinc-700 bg-zinc-900 p-3"><option value="whatsapp">WhatsApp automation</option><option value="instagram">Instagram automation</option><option value="both">Both channels</option></select>{errors.scope && <span id="scope-error" role="alert" className="mt-1 block text-xs text-amber-200">{errors.scope}</span>}</label><h2 className="pt-3 font-semibold">3. Access</h2><p className="text-sm leading-6 text-zinc-400">Generating the client creates a reusable access link, valid for 24 hours. Copy or share it now; it can be opened again throughout that window.</p><ActionButton label="Generate access link" loadingLabel="Generating link…" successLabel="Link generated" className="rounded-md bg-zinc-100 px-4 py-2.5 text-sm font-semibold text-zinc-950" /></section><aside className="h-fit rounded-xl border border-zinc-800 p-6"><p className="text-sm font-semibold">Client preview</p><p className="mt-3 text-sm leading-6 text-zinc-400">Your client will see only the Meta service they bought, a short explanation before Meta opens, and a calm status while Volitex completes the technical setup.</p></aside></form>;
}
function Field({ label, name, type = "text", required = false, placeholder, error }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string; error?: string }) { const errorId = `${name}-error`; return <label className="block text-sm">{label}{required && <span className="text-amber-200"> *</span>}<input name={name} type={type} placeholder={placeholder} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} className="mt-2 w-full rounded-md border border-zinc-700 bg-zinc-900 p-3" />{error && <span id={errorId} role="alert" className="mt-1 block text-xs text-amber-200">{error}</span>}</label>; }
