"use server";
import bcrypt from "bcryptjs";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createAdminSession, clearAdminSession, requireAdmin } from "@/lib/auth";
import { createAccessLink } from "@/lib/client-access";
import { randomToken } from "@/lib/crypto";
import { database } from "@/lib/supabase";
import { disconnect } from "@/lib/connection";
const get = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
const providers = (scope: string) => scope === "both" ? ["whatsapp", "instagram"] : [scope];
async function audit(adminId: string, tenantId: string | null, eventType: string, details: Record<string, unknown> = {}) { await database().from("admin_audit_events").insert({ admin_id: adminId, tenant_id: tenantId, event_type: eventType, details }); }
export async function adminLogin(form: FormData): Promise<{ ok: true } | { error: string }> { const email = get(form, "email").toLowerCase(); const password = String(form.get("password") ?? ""); const { data } = await database().from("admin_users").select("id, email, password_hash, role, is_active").eq("email", email).maybeSingle(); if (!data?.is_active || !(await bcrypt.compare(password, data.password_hash))) return { error: "Invalid email or password" }; await createAdminSession({ adminId: data.id, email: data.email, role: data.role, sessionId: randomToken() }); return { ok: true }; }
export async function adminLogout() { await clearAdminSession(); redirect("/admin/login"); }
export async function createClient(form: FormData) { const admin = await requireAdmin(); const clientName = get(form, "clientName"); const email = get(form, "email").toLowerCase(); const scope = get(form, "scope"); if (!clientName || !email || !["whatsapp", "instagram", "both"].includes(scope)) redirect("/admin/clients/new?error=Complete%20the%20required%20fields"); const { data: tenant, error } = await database().from("tenants").insert({ client_name: clientName, primary_contact_name: get(form, "contactName") || null, primary_contact_email: email, client_type: get(form, "clientType") || null, market_code: get(form, "market") || null, timezone: get(form, "timezone") || null, locale: get(form, "locale") || null, internal_note: get(form, "note") || null, sales_owner: get(form, "owner") || null }).select("id").single(); if (error || !tenant) redirect("/admin/clients/new?error=Unable%20to%20create%20client"); const { error: serviceError } = await database().from("tenant_services").insert(providers(scope).map((provider) => ({ tenant_id: tenant.id, provider, status: "invite_sent", enabled_at: new Date().toISOString() }))); if (serviceError) redirect("/admin/clients/new?error=Unable%20to%20save%20service%20scope"); await createAccessLink(tenant.id, admin.adminId); await audit(admin.adminId, tenant.id, "client_created", { scope }); redirect(`/admin/clients/${tenant.id}`); }
export async function generateLink(form: FormData) { const admin = await requireAdmin(); const tenantId = get(form, "tenantId"); await createAccessLink(tenantId, admin.adminId); await audit(admin.adminId, tenantId, "access_link_generated"); redirect(`/admin/clients/${tenantId}`); }
export async function updateClient(form: FormData) { const admin = await requireAdmin(); const tenantId = get(form, "tenantId"); await database().from("tenants").update({ client_name: get(form, "clientName"), primary_contact_name: get(form, "contactName") || null, primary_contact_email: get(form, "email") || null, market_code: get(form, "market") || null, timezone: get(form, "timezone") || null, internal_note: get(form, "note") || null, portal_access_paused: get(form, "paused") === "on" }).eq("id", tenantId); await audit(admin.adminId, tenantId, "client_updated", { paused: get(form, "paused") === "on" }); revalidatePath(`/admin/clients/${tenantId}`); revalidatePath("/admin/clients"); }
export async function updateScope(form: FormData) { const admin = await requireAdmin(); const tenantId = get(form, "tenantId"); const scope = get(form, "scope"); if (!["whatsapp", "instagram", "both"].includes(scope)) return; const wanted = providers(scope); const { data: existing } = await database().from("tenant_services").select("provider").eq("tenant_id", tenantId); for (const provider of wanted) { if (!existing?.some((item) => item.provider === provider)) await database().from("tenant_services").insert({ tenant_id: tenantId, provider, status: "not_started", enabled_at: new Date().toISOString() }); else await database().from("tenant_services").update({ status: "not_started" }).eq("tenant_id", tenantId).eq("provider", provider).eq("status", "disabled"); } for (const item of existing ?? []) if (!wanted.includes(item.provider)) await database().from("tenant_services").update({ status: "disabled" }).eq("tenant_id", tenantId).eq("provider", item.provider); await audit(admin.adminId, tenantId, "service_scope_updated", { scope }); revalidatePath(`/admin/clients/${tenantId}`); revalidatePath("/admin/clients"); }
export async function updateLifecycle(form: FormData) { const admin = await requireAdmin(); const tenantId = get(form, "tenantId"); const status = get(form, "status"); const values: Record<string, unknown> = { status, status_note: get(form, "note") || null }; if (status === "live") values.live_at = new Date().toISOString(); await database().from("tenant_services").update(values).eq("tenant_id", tenantId).eq("provider", get(form, "provider")); await audit(admin.adminId, tenantId, "lifecycle_updated", { provider: get(form, "provider"), status }); revalidatePath(`/admin/clients/${tenantId}`); revalidatePath("/admin/activation"); }
export async function removeConnection(form: FormData) { const admin = await requireAdmin(); const tenantId = get(form, "tenantId"); const provider = get(form, "provider"); if (get(form, "confirm") !== "remove" || (provider !== "whatsapp" && provider !== "instagram")) return; await disconnect(tenantId, provider); await database().from("tenant_services").update({ status: "not_started", connected_at: null, status_note: "Connection removed by Volitex" }).eq("tenant_id", tenantId).eq("provider", provider); await audit(admin.adminId, tenantId, "connection_removed", { provider }); revalidatePath(`/admin/clients/${tenantId}`); }
export async function toggleClientAccess(tenantId: string) { const admin = await requireAdmin(); const { data: tenant } = await database().from("tenants").select("portal_access_paused").eq("id", tenantId).single(); if (!tenant) return { error: "Client not found" }; const paused = !tenant.portal_access_paused; const { error } = await database().from("tenants").update({ portal_access_paused: paused }).eq("id", tenantId); if (error) return { error: "Unable to update access" }; await audit(admin.adminId, tenantId, paused ? "client_access_paused" : "client_access_resumed"); revalidatePath("/admin/clients"); return { paused } as const; }
export async function deleteClient(tenantId: string) { const admin = await requireAdmin(); const { error } = await database().from("tenants").delete().eq("id", tenantId); if (error) return { error: "Unable to delete this client. Check for dependent records and try again." }; await audit(admin.adminId, null, "client_deleted", { tenantId }); revalidatePath("/admin/clients"); return { deleted: true } as const; }
